apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envquery.fullname" . }}
  labels:
    {{- include "envquery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "envquery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "envquery.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "envquery.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          {{- toYaml .Values.containerArgs | nindent 8 }}
        env:
        - name: JWT_PUBKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret.name }}
              key: {{ .Values.existingSecret.key }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /config.yaml
          subPath: config.yaml          
      volumes:
      - name: config
        configMap:
          name: nginx-subrequest-auth-jwt-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
