{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envquery.serviceAccountName" . }}
  labels:
{{ include "envquery.labels" . | nindent 4 }}
{{- end -}}
