apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-subrequest-auth-jwt-config
  labels:
    app: nginx-subrequest-auth-jwt
data:
  config.yaml: |
  	validationKeys:
    - type: ecPublicKey
      key: |
        -----BEGIN PUBLIC KEY-----
        <FILL IN YOUR PUBLIC KEY HERE>
        -----END PUBLIC KEY-----
    claims:
    - groups:
      - developers
      - administrators

