apiVersion: v1
kind: Service
metadata:
  name: nginx-subrequest-auth-jwt
  labels:
    app: nginx-subrequest-auth-jwt
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-subrequest-auth-jwt
